### ISSUE TITLE
problem with global listening and listening on specific port

### ISSUE THREAD

**Issue by thepwnexperts** [thepwnexperts/m1-sm2-u1#1]
check out 
1) https://github.com/thepwnexperts/m1-sm1-u1/blob/main/vite.config.js
2) https://github.com/thepwnexperts/m1-sm1-u1/blob/main/package.json

**Comment by ajshrmaofficial** [comment]
Issue fixed in commit fc3eddbea11beded1359ce7a0ffae4d3dce79256
